{:dev  {:env {:dcs            "10"
              :stores         "200"
              :products       "1000"
              :days           "1"
              :plans          "./plans/"
              :solver-procs   "7"
              :assemble-procs "4"
              :forecast-procs "2"}}
 :test {:env {:dcs            "1"
              :stores         "2"
              :products       "1"
              :days           "10"
              :plans          "./plans"
              :solver-procs   "1"
              :assemble-procs "1"
              :forecast-procs "2"}}}